artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url : https://github.com/shabbu8111999/Dataset_Repo_/raw/refs/heads/main/Book%20dataset.zip
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data


data_validation_config:
  clean_data_dir: clean_data
  serialized_objects_dir: serialized_objects
  books_csv_file: BX-Books.csv
  ratings_csv_file: BX-Book-Ratings.csv 